# Generated by Django 2.0 on 2019-06-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['pub_time'],
            },
        ),
    ]
